version: 2.1

jobs:
  build:
    working_directory: ~/CircleCi
    docker:
      - image: "circleci/python"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/CircleCi
    docker:
    - image: "circleci/python"
    steps:
      - checkout
      - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build